apiVersion: v1
kind: Service                    
metadata:
  name: ga-frontend-service   
spec:
  type: LoadBalancer                
  ports:                         
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: ga-frontend   