name: Build and Deploy to GKE

on:
  pull_request:
    branches:
      - master
    types:
      - closed

env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  PROJECT_ID: grasys-study
  GKE_CLUSTER: ga-gke   
  GKE_ZONE: asia-northeast1-a
  DEPLOYMENT_NAME: ga-backend
  IMAGE: static-site
  REGION: asia-northeast1
  GAR_LOCATION: asia-northeast1-docker.pkg.dev/containers/ga-backend


jobs:
  notify-started:
    uses: ./.github/workflows/_notify_started.yaml
    secrets: inherit  

  setup-scan-build-scan-publish-deploy:
    name: Setup Scan Build Scan Publish Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: notify-started

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker 
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA"

    - name: Run trivy for docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "asia-northeast1-docker.pkg.dev/ga-backend:$GITHUB_SHA"
        format: 'sarif'
        output: 'trivy-results.sarif'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/ga-backend:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

  notify-finished:
    if: always()
    needs: setup-scan-build-scan-publish-deploy
    uses: ./.github/workflows/_notify_finished.yaml
    secrets: inherit
